[config]
schemaVersion = "0.0.1"

[package]
namespace = "MT2"
name = "Trainworks.Reloaded"
versionNumber = "0.0.1"
description = "A Data Load and Injection Engine for Monster Train 2"
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack-5.4.2100 = "5.4.2100"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "mt2", ]
[publish.categories]
mt2 = [ "items", "skills", ]


