name: Release Build

on:
  release:
    types: [created]

permissions:
    packages: write
    
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Release]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Compatible with netstandard2.1

      - name: Extract Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Setup NuGet Credentials
        run: |
          dotnet nuget update source monster-train-packages -u USERNAME -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      
      - name: Restore Dependencies
        run: dotnet restore
      
      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution with Versioning
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore /p:Version=${VERSION}

      - name: Build Plugin
        run: dotnet publish TrainworksReloaded.Plugin/TrainworksReloaded.Plugin.csproj --configuration Release --output ./plugin_build /p:Version=${VERSION}

      - name: Zip Plugin
        run: zip -r TrainworksReloaded.Plugin.zip ./plugin_build

      - name: Get Release ID
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Plugin to Existing GitHub Release
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./TrainworksReloaded.Plugin.zip
          asset_name: TrainworksReloaded.Plugin.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}